on:
  workflow_dispatch:

name: Snyk IaC PR Diff Scan

on:
  pull_request:
   branches: [ master ]

permissions:
  contents: read

jobs:
  snyk-pipeline:
    runs-on: ubuntu-latest
    name: Snyk IaC PR Diff Scan
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    # Checkout base ref branch
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        ref: ${{ github.base_ref }}
    - name: Download Snyk
      run: |
         wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
         chmod +x ./snyk
         mv ./snyk /usr/local/bin/

    - name: Authenticate Snyk
      run: snyk auth ${SNYK_TOKEN}

    - name: Run Snyk IaC Test
      run: snyk iac test --json > ${{ github.workspace }}/snyk_iac_baseline.json
      continue-on-error: true

    # Upload the Snyk IaC results from the main branch
    - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
      with:
         name: snyk_iac_baseline
         path: ${{ github.workspace }}/snyk_iac_baseline.json

    # Checkout PR branch
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Authenticate Snyk
      run: snyk auth ${SNYK_TOKEN}
 
    - name: Run IaC Test
      run: |
        sleep 10s
        snyk iac test --json > ${{ github.workspace }}/snyk_iac_pr.json || true
      continue-on-error: true

    # Upload the Snyk IaC results from the PR scan
    - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
      with:
          name: snyk_iac_pr
          path: ${{ github.workspace }}/snyk_iac_pr.json

    - uses: actions/download-artifact@v4 
      with:
        name: snyk_iac_baseline
    - name: Download Binary
      run: |
        cd "${{ github.workspace }}/.github"
        curl -LJO https://github.com/snyk-playground/cx-tools/raw/main/snyk-pr-diff/bin/snyk-pr-diff-amd64-linux
    - name: Run PR check 
      run: |
        chmod +x "${{ github.workspace }}/.github/snyk-pr-diff-amd64-linux"
        ${{ github.workspace }}/.github/snyk-pr-diff-amd64-linux iac ${{ github.workspace }}/snyk_iac_baseline.json ${{ github.workspace }}/snyk_iac_pr.json
    - name: Debugging
      run: |
        ls -l "${{ github.workspace }}/.github/"  
        ls "${{ github.workspace }}/.github/workflows"
 
       
